# Generated by Django 5.0.7 on 2024-07-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mensagem', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('tipo_hamburguer', models.CharField(choices=[('classico', 'Clássico'), ('cheddar_bacon', 'Cheddar Bacon'), ('vegetariano', 'Vegetariano'), ('frango', 'Frango')], max_length=50)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
